"""family profiles and taxon summaries

Revision ID: 22a684a64723
Revises: ee20df877b61
Create Date: 2026-10-09 13:38:20.210410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22a684a64723'
down_revision: Union[str, Sequence[str], None] = 'ee20df877b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family', sa.String(length=255), nullable=False),
    sa.Column('species_count', sa.Integer(), nullable=True),
    sa.Column('checklist_release', sa.String(length=50), nullable=True),
    sa.Column('range_geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('range_species_mapped', sa.Integer(), nullable=True),
    sa.Column('rep_scientific_name', sa.String(length=255), nullable=True),
    sa.Column('rep_range_geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('range_source', sa.String(length=100), nullable=True),
    sa.Column('range_citation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_profiles_family'), 'family_profiles', ['family'], unique=True)
    op.create_table('taxon_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('extract', sa.Text(), nullable=False),
    sa.Column('revision', sa.String(length=50), nullable=True),
    sa.Column('licence', sa.String(length=50), nullable=False),
    sa.Column('licence_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxon_summaries_name'), 'taxon_summaries', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taxon_summaries_name'), table_name='taxon_summaries')
    op.drop_table('taxon_summaries')
    op.drop_index(op.f('ix_family_profiles_family'), table_name='family_profiles')
    op.drop_table('family_profiles')
    # ### end Alembic commands ###
