"""initial schema

Revision ID: d691b18aa0e0
Revises: 
Create Date: 2026-09-18 21:14:28.930206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd691b18aa0e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_version', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taxa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('scientific_name', sa.String(length=255), nullable=False),
    sa.Column('rank', sa.String(length=50), nullable=False),
    sa.Column('col_taxon_id', sa.String(length=100), nullable=True),
    sa.Column('taxonomic_source', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['taxa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxa_col_taxon_id'), 'taxa', ['col_taxon_id'], unique=False)
    op.create_index(op.f('ix_taxa_parent_id'), 'taxa', ['parent_id'], unique=False)
    op.create_index(op.f('ix_taxa_scientific_name'), 'taxa', ['scientific_name'], unique=False)
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taxon_id', sa.Integer(), nullable=True),
    sa.Column('scientific_name', sa.String(length=255), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=True),
    sa.Column('accepted_name', sa.String(length=255), nullable=True),
    sa.Column('col_taxon_id', sa.String(length=100), nullable=True),
    sa.Column('gbif_taxon_id', sa.Integer(), nullable=True),
    sa.Column('ott_id', sa.Integer(), nullable=True),
    sa.Column('iucn_category', sa.String(length=10), nullable=True),
    sa.Column('iucn_assessment_year', sa.Integer(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['taxon_id'], ['taxa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_col_taxon_id'), 'species', ['col_taxon_id'], unique=False)
    op.create_index(op.f('ix_species_gbif_taxon_id'), 'species', ['gbif_taxon_id'], unique=False)
    op.create_index(op.f('ix_species_ott_id'), 'species', ['ott_id'], unique=False)
    op.create_index(op.f('ix_species_scientific_name'), 'species', ['scientific_name'], unique=True)
    op.create_index(op.f('ix_species_taxon_id'), 'species', ['taxon_id'], unique=False)
    op.create_table('occurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('basis_of_record', sa.String(length=100), nullable=True),
    sa.Column('dataset', sa.String(length=255), nullable=True),
    sa.Column('gbif_id', sa.Integer(), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occurrences_gbif_id'), 'occurrences', ['gbif_id'], unique=False)
    op.create_index(op.f('ix_occurrences_species_id'), 'occurrences', ['species_id'], unique=False)
    op.create_table('phylogeny_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_species_id', sa.Integer(), nullable=True),
    sa.Column('child_species_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['child_species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['parent_species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phylogeny_edges_child_species_id'), 'phylogeny_edges', ['child_species_id'], unique=False)
    op.create_index(op.f('ix_phylogeny_edges_parent_species_id'), 'phylogeny_edges', ['parent_species_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phylogeny_edges_parent_species_id'), table_name='phylogeny_edges')
    op.drop_index(op.f('ix_phylogeny_edges_child_species_id'), table_name='phylogeny_edges')
    op.drop_table('phylogeny_edges')
    op.drop_index(op.f('ix_occurrences_species_id'), table_name='occurrences')
    op.drop_index(op.f('ix_occurrences_gbif_id'), table_name='occurrences')
    op.drop_table('occurrences')
    op.drop_index(op.f('ix_species_taxon_id'), table_name='species')
    op.drop_index(op.f('ix_species_scientific_name'), table_name='species')
    op.drop_index(op.f('ix_species_ott_id'), table_name='species')
    op.drop_index(op.f('ix_species_gbif_taxon_id'), table_name='species')
    op.drop_index(op.f('ix_species_col_taxon_id'), table_name='species')
    op.drop_table('species')
    op.drop_index(op.f('ix_taxa_scientific_name'), table_name='taxa')
    op.drop_index(op.f('ix_taxa_parent_id'), table_name='taxa')
    op.drop_index(op.f('ix_taxa_col_taxon_id'), table_name='taxa')
    op.drop_table('taxa')
    op.drop_table('sources')
    # ### end Alembic commands ###
