"""taxon summary range text

Revision ID: ea0d9cbde512
Revises: 22a684a64723
Create Date: 2026-10-09 14:47:03.981333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea0d9cbde512'
down_revision: Union[str, Sequence[str], None] = '22a684a64723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxon_summaries', sa.Column('range_text', sa.Text(), nullable=True))
    op.add_column('taxon_summaries', sa.Column('range_scope', sa.String(length=20), nullable=True))
    op.add_column('taxon_summaries', sa.Column('range_title', sa.String(length=255), nullable=True))
    op.add_column('taxon_summaries', sa.Column('range_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taxon_summaries', 'range_url')
    op.drop_column('taxon_summaries', 'range_title')
    op.drop_column('taxon_summaries', 'range_scope')
    op.drop_column('taxon_summaries', 'range_text')
    # ### end Alembic commands ###
